Gpt_41_nano = "openai/gpt-4.1-nano"
Gpt_41_mini = "openai/gpt-4.1-mini"
Claude_35_haiku = "anthropic/claude-3.5-haiku"
Claude_37_sonnet = "anthropic/claude-3.7-sonnet"
Gemini_25_Flash_Preview_thinking = "google/gemini-2.5-flash-preview:thinking"
deepseek_deepseek_r1 = "deepseek/deepseek-r1"
Gemini_20_flash_001 = "google/gemini-2.0-flash-001"

free_mistral_Small_31_24B = "mistralai/mistral-small-3.1-24b-instruct:free"
free_deepSeek_V3_Base = "deepseek/deepseek-v3-base:free"
free_meta_Llama_4_Maverick = "meta-llama/llama-4-maverick:free"
free_nous_Hermes_3_Mistral_24B = "nousresearch/deephermes-3-mistral-24b-preview:free"
free_gemini_20_flash_exp = "google/gemini-2.0-flash-exp:free"
