research_task:
  name: Research Task
  description: >
    Conduct thorough research on company {company}. Focus on:
    1. Current company status and health
    2. Historical company performance
    3. Major challenges and opportunities
    4. Recent news and events
    5. Future outlook and potential developments

    Make sure to organize your findings in a structured format with clear sections.
  expected_output: >
    A comprehensive research document with a well-organized sections covering
    all the requested aspects of the company {company}. Include specific facts, figures
    and examples where relevant.
  agent: financial_researcher

analysis_task:
  name: Analysis Task
  description: >
    Analyze the research findings and create a comprehensive report on {company}.
    Your report should:
    1. Begin with an executive summary
    2. Include all key information from the research
    3. Provide insightful analysis of trends and patterns
    4. Offer a market outlook for company, noting that this should not be used for trading decisions
    5. Be formatted in a professional, easy-to-read style with clear headings
  expected_output: >
    A polished, professional report on {company} that presents the reseach findings
    with added analysis and insights. The report should be well-structured with an executive summary,
    main sections and conclusion.
  agent: financial_analyst
  context:
    - research_task
  output_file: output/report.md
